# Generated by Django 4.2.7 on 2023-11-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum van activiteit')),
                ('event_start', models.TimeField(verbose_name='Begintijd')),
                ('event_end', models.TextField(verbose_name='Eindtijd')),
                ('note', models.CharField(max_length=200, verbose_name='Omschrijving')),
                ('costs', models.CharField(max_length=200, verbose_name='Kosten')),
            ],
        ),
    ]
